package Vista;

import Control.Arbol;
import Control.Nodo;
import Modelo.AGENDA;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JDialogo_Principal extends javax.swing.JDialog {

    Arbol arbol = new Arbol();
    String[] Cabecera = {"APELLIDOS", "NOMBRES", "TELEFONO"};
    DefaultTableModel modTabla = new DefaultTableModel(Cabecera, 0);
   
    
    public JDialogo_Principal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         Estado_Controles(false);
         
         Tbl_Datos.setModel(modTabla);
        setLocationRelativeTo(null);
        
         modTabla = (DefaultTableModel) Tbl_Datos.getModel();    
    }
    
    public void Limpiar_Controles()
    {
        Txt_Apellidos.setText("");
        Txt_Nombres.setText("");
        Txt_Telefono.setText("");
    }
    
    public final void Estado_Controles(boolean Estado)
    {
        Txt_Apellidos.setEnabled(Estado);
        Txt_Nombres.setEnabled(Estado);
        Txt_Telefono.setEnabled(Estado);
        Btn_Eliminar.setEnabled(Estado);    
        Btn_Agregar.setEnabled(Estado);
        Btn_Buscar.setEnabled(Estado);
        Btn_CerrarSesion.setEnabled(Estado);
        Btn_Editar.setEnabled(Estado);  
        Btn_Cancelar.setEnabled(Estado);
        
        
        Tbl_Datos.setEnabled(Estado);
    }

    public void Limpiar_Tabla(){
        while (modTabla.getRowCount()>0) {            
            modTabla.removeRow(0);
        }
    }
    
    public void CargarDatos(Nodo Auxiliar)
    {
         if(Auxiliar != null) {
              Txt_Apellidos.setText(Auxiliar.getElemento().getApellidos());    
              Txt_Nombres.setText(Auxiliar.getElemento().getNombres());  
              Txt_Telefono.setText(Auxiliar.getElemento().getTelefono()+"");
                  
         }
    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_Nombres = new javax.swing.JTextField();
        Txt_Telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Datos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Btn_Agregar = new javax.swing.JButton();
        Btn_Editar = new javax.swing.JButton();
        Btn_Buscar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_CerrarSesion = new javax.swing.JButton();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Apellidos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Txt_Nombres.setText("                       ");

        Txt_Telefono.setText("                           ");
        Txt_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_TelefonoActionPerformed(evt);
            }
        });

        Tbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tbl_Datos);

        jPanel1.setLayout(new java.awt.GridLayout(7, 0, 0, 5));

        Btn_Agregar.setText("AGREGAR");
        Btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Agregar);

        Btn_Editar.setText("Editar/Actualizar");
        Btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Editar);

        Btn_Buscar.setText("Buscar");
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Buscar);

        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Eliminar);

        Btn_CerrarSesion.setText("Cerrar Sesion");
        Btn_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_CerrarSesion);

        Btn_Nuevo.setText("Nuevo");
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Nuevo);

        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Cancelar);

        jLabel1.setText("Apelliddos:");

        jLabel2.setText("Nombres:");

        jLabel3.setText("Telefono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_Apellidos)
                    .addComponent(Txt_Nombres)
                    .addComponent(Txt_Telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Txt_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_TelefonoActionPerformed

    private void Btn_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CerrarSesionActionPerformed
            dispose();
    }//GEN-LAST:event_Btn_CerrarSesionActionPerformed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        Estado_Controles(true);
        Limpiar_Controles();
        
        Txt_Apellidos.requestFocus();
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditarActionPerformed
         if(modTabla.getRowCount() > 0)
         {
             Estado_Controles(true);
             
             Txt_Apellidos.requestFocus();
         }
    }//GEN-LAST:event_Btn_EditarActionPerformed

    private void Btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarActionPerformed
         Object[] Registro = {Txt_Apellidos.getText(),Txt_Nombres.getText(),Txt_Telefono.getText()};
         
         AGENDA Elemento = new AGENDA(Registro);
         arbol.setRaiz(arbol.Agregar(arbol.getRaiz(), Elemento));
         
         Limpiar_Tabla();
            arbol.Listar_inOrden(modTabla, arbol.getRaiz());
         Limpiar_Controles();
            Estado_Controles(false);
         
    }//GEN-LAST:event_Btn_AgregarActionPerformed

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
        Limpiar_Controles();
            Estado_Controles(false);
    }//GEN-LAST:event_Btn_CancelarActionPerformed

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
         String Cadena = JOptionPane.showInputDialog("Ingresar Nombre : ");
          Nodo Auxiliar = arbol.BuscarApeNom(Cadena);
           if(Auxiliar != null) 
                CargarDatos(Auxiliar); 
           else{
            JOptionPane.showMessageDialog(this, "NO EXISTE");
           }
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
         int Fila = Tbl_Datos.getSelectedRow(); 
          if(Fila != -1) {
               String Cadena = modTabla.getValueAt(Fila, 0) + " " + modTabla.getValueAt(Fila, 1); 
                arbol.setRaiz(arbol.Eliminar(arbol.getRaiz(),Cadena));
                Limpiar_Tabla();
                 arbol.Listar_inOrden(modTabla, arbol.getRaiz()); 
          }
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogo_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogo_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogo_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogo_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogo_Principal dialog = new JDialogo_Principal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Agregar;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_CerrarSesion;
    private javax.swing.JButton Btn_Editar;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JTable Tbl_Datos;
    private javax.swing.JTextField Txt_Apellidos;
    private javax.swing.JTextField Txt_Nombres;
    private javax.swing.JTextField Txt_Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
